/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type ClickatellSettingDto = {
  clickatellHost?: string | null;
  clickatellApiUsername?: string | null;
  clickatellApiPassword?: string | null;
  clickatellApiId?: string | null;
} | null;

export type ValidationErrorInfo = {
  message?: string | null;
  members?: string | null[] | null;
} | null;

export type ErrorInfo = {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
} | null;

export type BooleanAjaxResponse = {
  result?: boolean;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type AjaxResponseBase = {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type ClickatellSettingDtoAjaxResponse = {
  result?: ClickatellSettingDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type ClickatellUpdateSettingsProps = Omit<
  MutateProps<BooleanAjaxResponse, AjaxResponseBase, void, ClickatellSettingDto>,
  'path' | 'verb'
>;

export const ClickatellUpdateSettings = (props: ClickatellUpdateSettingsProps) => (
  <Mutate<BooleanAjaxResponse, AjaxResponseBase, void, ClickatellSettingDto>
    verb="POST"
    path={`/api/services/app/Clickatell/UpdateSettings`}
    {...props}
  />
);

export type UseClickatellUpdateSettingsProps = Omit<
  UseMutateProps<BooleanAjaxResponse, void, ClickatellSettingDto>,
  'path' | 'verb'
>;

export const useClickatellUpdateSettings = (props: UseClickatellUpdateSettingsProps) =>
  useMutate<BooleanAjaxResponse, AjaxResponseBase, void, ClickatellSettingDto>(
    'POST',
    `/api/services/app/Clickatell/UpdateSettings`,
    props
  );

export type ClickatellGetSettingsProps = Omit<
  GetProps<ClickatellSettingDtoAjaxResponse, AjaxResponseBase, void>,
  'path'
>;

export const ClickatellGetSettings = (props: ClickatellGetSettingsProps) => (
  <Get<ClickatellSettingDtoAjaxResponse, AjaxResponseBase, void>
    path={`/api/services/app/Clickatell/GetSettings`}
    {...props}
  />
);

export type UseClickatellGetSettingsProps = Omit<UseGetProps<ClickatellSettingDtoAjaxResponse, void>, 'path'>;

export const useClickatellGetSettings = (props: UseClickatellGetSettingsProps) =>
  useGet<ClickatellSettingDtoAjaxResponse, AjaxResponseBase, void>(`/api/services/app/Clickatell/GetSettings`, props);
