/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type LdapSettingsDto = {
  isEnabled?: boolean;
  server?: string | null;
  port?: number;
  useSsl?: boolean;
  domain?: string | null;
} | null;

export type ValidationErrorInfo = {
  message?: string | null;
  members?: string | null[] | null;
} | null;

export type ErrorInfo = {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
} | null;

export type LdapSettingsDtoAjaxResponse = {
  result?: LdapSettingsDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type AjaxResponseBase = {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type LdapUpdateSettingsProps = Omit<MutateProps<void, unknown, void, LdapSettingsDto>, 'path' | 'verb'>;

export const LdapUpdateSettings = (props: LdapUpdateSettingsProps) => (
  <Mutate<void, unknown, void, LdapSettingsDto>
    verb="PUT"
    path={`/api/services/SheshaLdap/Ldap/UpdateSettings`}
    {...props}
  />
);

export type UseLdapUpdateSettingsProps = Omit<UseMutateProps<void, void, LdapSettingsDto>, 'path' | 'verb'>;

export const useLdapUpdateSettings = (props: UseLdapUpdateSettingsProps) =>
  useMutate<void, unknown, void, LdapSettingsDto>('PUT', `/api/services/SheshaLdap/Ldap/UpdateSettings`, props);

export interface LdapGetSettingsQueryParams {
  IsEnabled?: boolean;
  Server?: string | null;
  Port?: number;
  UseSsl?: boolean;
  Domain?: string | null;
}

export type LdapGetSettingsProps = Omit<
  GetProps<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams>,
  'path'
>;

export const LdapGetSettings = (props: LdapGetSettingsProps) => (
  <Get<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams>
    path={`/api/services/SheshaLdap/Ldap/GetSettings`}
    {...props}
  />
);

export type UseLdapGetSettingsProps = Omit<
  UseGetProps<LdapSettingsDtoAjaxResponse, LdapGetSettingsQueryParams>,
  'path'
>;

export const useLdapGetSettings = (props: UseLdapGetSettingsProps) =>
  useGet<LdapSettingsDtoAjaxResponse, AjaxResponseBase, LdapGetSettingsQueryParams>(
    `/api/services/SheshaLdap/Ldap/GetSettings`,
    props
  );
