/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type MobileDeviceDto = {
  name?: string | null;
  imei?: string | null;
  isLocked?: boolean;
  id?: string;
} | null;

export type ValidationErrorInfo = {
  message?: string | null;
  members?: string | null[] | null;
} | null;

export type ErrorInfo = {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
} | null;

export type MobileDeviceDtoAjaxResponse = {
  result?: MobileDeviceDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type AjaxResponseBase = {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type MobileDeviceDtoPagedResultDto = {
  totalCount?: number;
  items?: MobileDeviceDto[] | null;
} | null;

export type MobileDeviceDtoPagedResultDtoAjaxResponse = {
  result?: MobileDeviceDtoPagedResultDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export interface MobileDeviceGetQueryParams {
  Id?: string;
}

export type MobileDeviceGetProps = Omit<
  GetProps<MobileDeviceDtoAjaxResponse, AjaxResponseBase, MobileDeviceGetQueryParams>,
  'path'
>;

export const MobileDeviceGet = (props: MobileDeviceGetProps) => (
  <Get<MobileDeviceDtoAjaxResponse, AjaxResponseBase, MobileDeviceGetQueryParams>
    path={`/api/services/app/MobileDevice/Get`}
    {...props}
  />
);

export type UseMobileDeviceGetProps = Omit<
  UseGetProps<MobileDeviceDtoAjaxResponse, MobileDeviceGetQueryParams>,
  'path'
>;

export const useMobileDeviceGet = (props: UseMobileDeviceGetProps) =>
  useGet<MobileDeviceDtoAjaxResponse, AjaxResponseBase, MobileDeviceGetQueryParams>(
    `/api/services/app/MobileDevice/Get`,
    props
  );

export interface MobileDeviceGetAllQueryParams {
  Sorting?: string | null;
  SkipCount?: number;
  MaxResultCount?: number;
}

export type MobileDeviceGetAllProps = Omit<
  GetProps<MobileDeviceDtoPagedResultDtoAjaxResponse, AjaxResponseBase, MobileDeviceGetAllQueryParams>,
  'path'
>;

export const MobileDeviceGetAll = (props: MobileDeviceGetAllProps) => (
  <Get<MobileDeviceDtoPagedResultDtoAjaxResponse, AjaxResponseBase, MobileDeviceGetAllQueryParams>
    path={`/api/services/app/MobileDevice/GetAll`}
    {...props}
  />
);

export type UseMobileDeviceGetAllProps = Omit<
  UseGetProps<MobileDeviceDtoPagedResultDtoAjaxResponse, MobileDeviceGetAllQueryParams>,
  'path'
>;

export const useMobileDeviceGetAll = (props: UseMobileDeviceGetAllProps) =>
  useGet<MobileDeviceDtoPagedResultDtoAjaxResponse, AjaxResponseBase, MobileDeviceGetAllQueryParams>(
    `/api/services/app/MobileDevice/GetAll`,
    props
  );

export type MobileDeviceCreateProps = Omit<
  MutateProps<MobileDeviceDtoAjaxResponse, AjaxResponseBase, void, MobileDeviceDto>,
  'path' | 'verb'
>;

export const MobileDeviceCreate = (props: MobileDeviceCreateProps) => (
  <Mutate<MobileDeviceDtoAjaxResponse, AjaxResponseBase, void, MobileDeviceDto>
    verb="POST"
    path={`/api/services/app/MobileDevice/Create`}
    {...props}
  />
);

export type UseMobileDeviceCreateProps = Omit<
  UseMutateProps<MobileDeviceDtoAjaxResponse, void, MobileDeviceDto>,
  'path' | 'verb'
>;

export const useMobileDeviceCreate = (props: UseMobileDeviceCreateProps) =>
  useMutate<MobileDeviceDtoAjaxResponse, AjaxResponseBase, void, MobileDeviceDto>(
    'POST',
    `/api/services/app/MobileDevice/Create`,
    props
  );

export type MobileDeviceUpdateProps = Omit<
  MutateProps<MobileDeviceDtoAjaxResponse, AjaxResponseBase, void, MobileDeviceDto>,
  'path' | 'verb'
>;

export const MobileDeviceUpdate = (props: MobileDeviceUpdateProps) => (
  <Mutate<MobileDeviceDtoAjaxResponse, AjaxResponseBase, void, MobileDeviceDto>
    verb="PUT"
    path={`/api/services/app/MobileDevice/Update`}
    {...props}
  />
);

export type UseMobileDeviceUpdateProps = Omit<
  UseMutateProps<MobileDeviceDtoAjaxResponse, void, MobileDeviceDto>,
  'path' | 'verb'
>;

export const useMobileDeviceUpdate = (props: UseMobileDeviceUpdateProps) =>
  useMutate<MobileDeviceDtoAjaxResponse, AjaxResponseBase, void, MobileDeviceDto>(
    'PUT',
    `/api/services/app/MobileDevice/Update`,
    props
  );

export interface MobileDeviceDeleteQueryParams {
  Id?: string;
}

export type MobileDeviceDeleteProps = Omit<
  MutateProps<void, unknown, MobileDeviceDeleteQueryParams, void>,
  'path' | 'verb'
>;

export const MobileDeviceDelete = (props: MobileDeviceDeleteProps) => (
  <Mutate<void, unknown, MobileDeviceDeleteQueryParams, void>
    verb="DELETE"
    path={`/api/services/app/MobileDevice/Delete`}
    {...props}
  />
);

export type UseMobileDeviceDeleteProps = Omit<
  UseMutateProps<void, MobileDeviceDeleteQueryParams, void>,
  'path' | 'verb'
>;

export const useMobileDeviceDelete = (props: UseMobileDeviceDeleteProps) =>
  useMutate<void, unknown, MobileDeviceDeleteQueryParams, void>(
    'DELETE',
    `/api/services/app/MobileDevice/Delete`,
    props
  );
