/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type ReferenceListItemValueDto = {
  item?: string | null;
  itemValue?: number | null;
} | null;

export type CreatePersonAccountDto = {
  userName: string;
  password: string;
  firstName: string;
  lastName: string;
  mobileNumber?: string | null;
  emailAddress: string;
  typeOfAccount?: ReferenceListItemValueDto;
} | null;

export type PersonAccountDto = {
  userName: string;
  firstName: string;
  lastName: string;
  mobileNumber?: string | null;
  emailAddress: string;
  typeOfAccount?: ReferenceListItemValueDto;
  id?: string;
} | null;

export type ValidationErrorInfo = {
  message?: string | null;
  members?: string | null[] | null;
} | null;

export type ErrorInfo = {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
} | null;

export type PersonAccountDtoAjaxResponse = {
  result?: PersonAccountDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type AjaxResponseBase = {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type AutocompleteItemDto = {
  value?: string | null;
  displayText?: string | null;
} | null;

export type AutocompleteItemDtoListAjaxResponse = {
  result?: AutocompleteItemDto[] | null;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type PersonAccountDtoPagedResultDto = {
  totalCount?: number;
  items?: PersonAccountDto[] | null;
} | null;

export type PersonAccountDtoPagedResultDtoAjaxResponse = {
  result?: PersonAccountDtoPagedResultDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type PersonCreateProps = Omit<
  MutateProps<PersonAccountDtoAjaxResponse, AjaxResponseBase, void, CreatePersonAccountDto>,
  'path' | 'verb'
>;

export const PersonCreate = (props: PersonCreateProps) => (
  <Mutate<PersonAccountDtoAjaxResponse, AjaxResponseBase, void, CreatePersonAccountDto>
    verb="POST"
    path={`/api/services/app/Person/Create`}
    {...props}
  />
);

export type UsePersonCreateProps = Omit<
  UseMutateProps<PersonAccountDtoAjaxResponse, void, CreatePersonAccountDto>,
  'path' | 'verb'
>;

export const usePersonCreate = (props: UsePersonCreateProps) =>
  useMutate<PersonAccountDtoAjaxResponse, AjaxResponseBase, void, CreatePersonAccountDto>(
    'POST',
    `/api/services/app/Person/Create`,
    props
  );

export interface PersonAutocompleteByNameQueryParams {
  term?: string | null;
}

export type PersonAutocompleteByNameProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, PersonAutocompleteByNameQueryParams>,
  'path'
>;

export const PersonAutocompleteByName = (props: PersonAutocompleteByNameProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, PersonAutocompleteByNameQueryParams>
    path={`/api/services/app/Person/AutocompleteByName`}
    {...props}
  />
);

export type UsePersonAutocompleteByNameProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, PersonAutocompleteByNameQueryParams>,
  'path'
>;

export const usePersonAutocompleteByName = (props: UsePersonAutocompleteByNameProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, PersonAutocompleteByNameQueryParams>(
    `/api/services/app/Person/AutocompleteByName`,
    props
  );

export type PersonUpdateProps = Omit<
  MutateProps<PersonAccountDtoAjaxResponse, AjaxResponseBase, void, PersonAccountDto>,
  'path' | 'verb'
>;

export const PersonUpdate = (props: PersonUpdateProps) => (
  <Mutate<PersonAccountDtoAjaxResponse, AjaxResponseBase, void, PersonAccountDto>
    verb="PUT"
    path={`/api/services/app/Person/Update`}
    {...props}
  />
);

export type UsePersonUpdateProps = Omit<
  UseMutateProps<PersonAccountDtoAjaxResponse, void, PersonAccountDto>,
  'path' | 'verb'
>;

export const usePersonUpdate = (props: UsePersonUpdateProps) =>
  useMutate<PersonAccountDtoAjaxResponse, AjaxResponseBase, void, PersonAccountDto>(
    'PUT',
    `/api/services/app/Person/Update`,
    props
  );

export interface PersonGetQueryParams {
  Id?: string;
}

export type PersonGetProps = Omit<
  GetProps<PersonAccountDtoAjaxResponse, AjaxResponseBase, PersonGetQueryParams>,
  'path'
>;

export const PersonGet = (props: PersonGetProps) => (
  <Get<PersonAccountDtoAjaxResponse, AjaxResponseBase, PersonGetQueryParams>
    path={`/api/services/app/Person/Get`}
    {...props}
  />
);

export type UsePersonGetProps = Omit<UseGetProps<PersonAccountDtoAjaxResponse, PersonGetQueryParams>, 'path'>;

export const usePersonGet = (props: UsePersonGetProps) =>
  useGet<PersonAccountDtoAjaxResponse, AjaxResponseBase, PersonGetQueryParams>(`/api/services/app/Person/Get`, props);

export interface PersonGetAllQueryParams {
  Sorting?: string | null;
  SkipCount?: number;
  MaxResultCount?: number;
}

export type PersonGetAllProps = Omit<
  GetProps<PersonAccountDtoPagedResultDtoAjaxResponse, AjaxResponseBase, PersonGetAllQueryParams>,
  'path'
>;

export const PersonGetAll = (props: PersonGetAllProps) => (
  <Get<PersonAccountDtoPagedResultDtoAjaxResponse, AjaxResponseBase, PersonGetAllQueryParams>
    path={`/api/services/app/Person/GetAll`}
    {...props}
  />
);

export type UsePersonGetAllProps = Omit<
  UseGetProps<PersonAccountDtoPagedResultDtoAjaxResponse, PersonGetAllQueryParams>,
  'path'
>;

export const usePersonGetAll = (props: UsePersonGetAllProps) =>
  useGet<PersonAccountDtoPagedResultDtoAjaxResponse, AjaxResponseBase, PersonGetAllQueryParams>(
    `/api/services/app/Person/GetAll`,
    props
  );

export interface PersonDeleteQueryParams {
  Id?: string;
}

export type PersonDeleteProps = Omit<MutateProps<void, unknown, PersonDeleteQueryParams, void>, 'path' | 'verb'>;

export const PersonDelete = (props: PersonDeleteProps) => (
  <Mutate<void, unknown, PersonDeleteQueryParams, void>
    verb="DELETE"
    path={`/api/services/app/Person/Delete`}
    {...props}
  />
);

export type UsePersonDeleteProps = Omit<UseMutateProps<void, PersonDeleteQueryParams, void>, 'path' | 'verb'>;

export const usePersonDelete = (props: UsePersonDeleteProps) =>
  useMutate<void, unknown, PersonDeleteQueryParams, void>('DELETE', `/api/services/app/Person/Delete`, props);
