/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type UtilManSettingsDto = {
  revisitPeriod?: number;
} | null;

export type ValidationErrorInfo = {
  message?: string | null;
  members?: string | null[] | null;
} | null;

export type ErrorInfo = {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
} | null;

export type UtilManSettingsDtoAjaxResponse = {
  result?: UtilManSettingsDto;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type AjaxResponseBase = {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
} | null;

export type UtilManSettingsUpdateProps = Omit<MutateProps<void, unknown, void, UtilManSettingsDto>, 'path' | 'verb'>;

export const UtilManSettingsUpdate = (props: UtilManSettingsUpdateProps) => (
  <Mutate<void, unknown, void, UtilManSettingsDto>
    verb="POST"
    path={`/api/services/utilityManagement/UtilManSettings/Update`}
    {...props}
  />
);

export type UseUtilManSettingsUpdateProps = Omit<UseMutateProps<void, void, UtilManSettingsDto>, 'path' | 'verb'>;

export const useUtilManSettingsUpdate = (props: UseUtilManSettingsUpdateProps) =>
  useMutate<void, unknown, void, UtilManSettingsDto>(
    'POST',
    `/api/services/utilityManagement/UtilManSettings/Update`,
    props
  );

export type UtilManSettingsGetProps = Omit<GetProps<UtilManSettingsDtoAjaxResponse, AjaxResponseBase, void>, 'path'>;

export const UtilManSettingsGet = (props: UtilManSettingsGetProps) => (
  <Get<UtilManSettingsDtoAjaxResponse, AjaxResponseBase, void>
    path={`/api/services/utilityManagement/UtilManSettings/Get`}
    {...props}
  />
);

export type UseUtilManSettingsGetProps = Omit<UseGetProps<UtilManSettingsDtoAjaxResponse, void>, 'path'>;

export const useUtilManSettingsGet = (props: UseUtilManSettingsGetProps) =>
  useGet<UtilManSettingsDtoAjaxResponse, AjaxResponseBase, void>(
    `/api/services/utilityManagement/UtilManSettings/Get`,
    props
  );
